import type {AssigneePerformance,ExecutiveMetrics,IncidentSnapshot,PriorityMetrics,ReportingTaskSnapshot,ReportingWindow} from "./types.js";
import type {TaskPriority} from "../domain/types.js";
const PRIORITIES:TaskPriority[]=["P1","P2","P3","P4"];
export class MetricsEngine{
 calculate(tasks:ReportingTaskSnapshot[],incidents:IncidentSnapshot[],window:ReportingWindow,now:Date):ExecutiveMetrics{
  const scoped=tasks.filter(t=>t.createdAt<window.to&&t.dueAt>=window.from),closed=scoped.filter(t=>t.status==="CLOSED"),open=scoped.filter(t=>!["CLOSED","CANCELLED"].includes(t.status)),overdue=open.filter(t=>t.dueAt<now),sla=closed.filter(t=>t.closedAt&&t.closedAt<=t.dueAt),delays=scoped.map(t=>delay(t,now));
  const byPriority=Object.fromEntries(PRIORITIES.map(p=>[p,this.priority(scoped.filter(t=>t.priority===p),now)])) as Record<TaskPriority,PriorityMetrics>;
  const people=this.people(scoped,now),active=incidents.filter(i=>["OPEN","ACKNOWLEDGED","IN_PROGRESS"].includes(i.status)),incWindow=incidents.filter(i=>i.createdAt>=window.from&&i.createdAt<window.to);
  return {window,totalTasks:scoped.length,openTasks:open.length,closedTasks:closed.length,overdueTasks:overdue.length,completionRate:rate(closed.length,scoped.length),slaRate:rate(sla.length,closed.length),averageDelayHours:avg(delays),medianDelayHours:med(delays),criticalOpenTasks:open.filter(t=>t.priority==="P1").length,openIncidents:active.length,criticalIncidents:active.filter(i=>i.severity==="CRITICAL").length,byPriority,topPerformers:[...people].sort((a,b)=>b.completionRate-a.completionRate||a.averageDelayHours-b.averageDelayHours).slice(0,5),highestRiskAssignees:[...people].sort((a,b)=>b.overdueOpen-a.overdueOpen||b.averageDelayHours-a.averageDelayHours).slice(0,5),recurringIncidentCategories:cats(incWindow).slice(0,10)};
 }
 private priority(v:ReportingTaskSnapshot[],now:Date):PriorityMetrics{const o=v.filter(t=>!["CLOSED","CANCELLED"].includes(t.status)),c=v.filter(t=>t.status==="CLOSED"),s=c.filter(t=>t.closedAt&&t.closedAt<=t.dueAt),d=v.map(t=>delay(t,now));return{total:v.length,open:o.length,closed:c.length,overdue:o.filter(t=>t.dueAt<now).length,completionRate:rate(c.length,v.length),slaRate:rate(s.length,c.length),averageDelayHours:avg(d),medianDelayHours:med(d)}}
 private people(v:ReportingTaskSnapshot[],now:Date):AssigneePerformance[]{const g=new Map<string,ReportingTaskSnapshot[]>();for(const t of v)g.set(t.assigneeId,[...(g.get(t.assigneeId)??[]),t]);return[...g].map(([assigneeId,x])=>{const c=x.filter(t=>t.status==="CLOSED"),o=x.filter(t=>!["CLOSED","CANCELLED"].includes(t.status)&&t.dueAt<now);return{assigneeId,assigned:x.length,closed:c.length,overdueOpen:o.length,completionRate:rate(c.length,x.length),averageDelayHours:avg(x.map(t=>delay(t,now)))}})}
}
function delay(t:ReportingTaskSnapshot,n:Date){const e=t.status==="CLOSED"&&t.closedAt?t.closedAt:n;return Math.max(0,(e.getTime()-t.dueAt.getTime())/3600000)} function rate(a:number,b:number){return b?rnd(a/b*100):0} function avg(v:number[]){return v.length?rnd(v.reduce((a,b)=>a+b,0)/v.length):0} function med(v:number[]){if(!v.length)return 0;const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return rnd(s.length%2?s[m]:(s[m-1]+s[m])/2)} function rnd(v:number){return Math.round(v*100)/100} function cats(v:IncidentSnapshot[]){const m=new Map<string,number>();for(const i of v)m.set(i.category,(m.get(i.category)??0)+1);return[...m].map(([category,count])=>({category,count})).sort((a,b)=>b.count-a.count)}
