"""initial application schema

Revision ID: 431439b9fde5
Revises:
Create Date: 2026-07-23 10:17:30.744762
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '431439b9fde5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profile_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('location_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('store_code', sa.String(length=128), nullable=True),
    sa.Column('website_uri', sa.String(length=2048), nullable=True),
    sa.Column('phone_numbers', sa.JSON(), nullable=False),
    sa.Column('regular_hours', sa.JSON(), nullable=False),
    sa.Column('storefront_address', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'location_id', name='uq_business_profile_location')
    )
    op.create_index(op.f('ix_business_profile_locations_account_id'), 'business_profile_locations', ['account_id'], unique=False)
    op.create_index(op.f('ix_business_profile_locations_brand'), 'business_profile_locations', ['brand'], unique=False)
    op.create_index(op.f('ix_business_profile_locations_location_id'), 'business_profile_locations', ['location_id'], unique=False)
    op.create_table('business_profile_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('location_id', sa.String(length=128), nullable=False),
    sa.Column('review_name', sa.String(length=512), nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=True),
    sa.Column('reviewer', sa.JSON(), nullable=False),
    sa.Column('star_rating', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_reply', sa.JSON(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_name', name='uq_business_profile_review_name')
    )
    op.create_index(op.f('ix_business_profile_reviews_account_id'), 'business_profile_reviews', ['account_id'], unique=False)
    op.create_index(op.f('ix_business_profile_reviews_brand'), 'business_profile_reviews', ['brand'], unique=False)
    op.create_index('ix_business_profile_reviews_location', 'business_profile_reviews', ['account_id', 'location_id'], unique=False)
    op.create_index(op.f('ix_business_profile_reviews_location_id'), 'business_profile_reviews', ['location_id'], unique=False)
    op.create_table('checklist_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.String(length=128), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('process_key', sa.String(length=64), nullable=False),
    sa.Column('gate_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('open', 'hold', 'ready_for_approval', 'approved', 'closed', name='checklistinstancedbstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_instances_gate_id'), 'checklist_instances', ['gate_id'], unique=False)
    op.create_index(op.f('ix_checklist_instances_instance_id'), 'checklist_instances', ['instance_id'], unique=True)
    op.create_index(op.f('ix_checklist_instances_object_id'), 'checklist_instances', ['object_id'], unique=False)
    op.create_index(op.f('ix_checklist_instances_process_key'), 'checklist_instances', ['process_key'], unique=False)
    op.create_index(op.f('ix_checklist_instances_role'), 'checklist_instances', ['role'], unique=False)
    op.create_index(op.f('ix_checklist_instances_template_id'), 'checklist_instances', ['template_id'], unique=False)
    op.create_table('checklist_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.String(length=128), nullable=False),
    sa.Column('process_key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('primary_role', sa.String(length=64), nullable=False),
    sa.Column('gate_id', sa.String(length=128), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_checklist_template_version')
    )
    op.create_index(op.f('ix_checklist_templates_checksum'), 'checklist_templates', ['checksum'], unique=False)
    op.create_index(op.f('ix_checklist_templates_gate_id'), 'checklist_templates', ['gate_id'], unique=False)
    op.create_index(op.f('ix_checklist_templates_primary_role'), 'checklist_templates', ['primary_role'], unique=False)
    op.create_index(op.f('ix_checklist_templates_process_key'), 'checklist_templates', ['process_key'], unique=False)
    op.create_index(op.f('ix_checklist_templates_template_id'), 'checklist_templates', ['template_id'], unique=False)
    op.create_table('integration_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_runs_entity_key'), 'integration_runs', ['entity_key'], unique=False)
    op.create_index(op.f('ix_integration_runs_source'), 'integration_runs', ['source'], unique=False)
    op.create_table('listing_sync_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('own_id', sa.String(length=128), nullable=False),
    sa.Column('remote_id', sa.String(length=128), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('last_payload', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_sync_records_own_id'), 'listing_sync_records', ['own_id'], unique=True)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=255), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('dimension_hash', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'entity_key', 'metric_date', 'dimension_hash', name='uq_metric_snapshot')
    )
    op.create_index(op.f('ix_metric_snapshots_brand'), 'metric_snapshots', ['brand'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_entity_key'), 'metric_snapshots', ['entity_key'], unique=False)
    op.create_index('ix_metric_snapshots_source_date', 'metric_snapshots', ['source', 'metric_date'], unique=False)
    op.create_table('operational_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=True),
    sa.Column('source_role', sa.String(length=64), nullable=True),
    sa.Column('gate_id', sa.String(length=128), nullable=True),
    sa.Column('checklist_template_id', sa.String(length=128), nullable=True),
    sa.Column('checklist_required', sa.Boolean(), nullable=False),
    sa.Column('source_version', sa.String(length=32), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_processes_checklist_template_id'), 'operational_processes', ['checklist_template_id'], unique=False)
    op.create_index(op.f('ix_operational_processes_family'), 'operational_processes', ['family'], unique=False)
    op.create_index(op.f('ix_operational_processes_gate_id'), 'operational_processes', ['gate_id'], unique=False)
    op.create_index(op.f('ix_operational_processes_process_key'), 'operational_processes', ['process_key'], unique=True)
    op.create_index(op.f('ix_operational_processes_source_checksum'), 'operational_processes', ['source_checksum'], unique=False)
    op.create_table('process_card_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'published', 'archived', name='processcardstatus'), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('checklist_template_id', sa.String(length=128), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_key', 'version', name='uq_process_card_version')
    )
    op.create_index(op.f('ix_process_card_versions_process_key'), 'process_card_versions', ['process_key'], unique=False)
    op.create_index(op.f('ix_process_card_versions_role'), 'process_card_versions', ['role'], unique=False)
    op.create_index(op.f('ix_process_card_versions_source_checksum'), 'process_card_versions', ['source_checksum'], unique=False)
    op.create_table('publication_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=False),
    sa.Column('website_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'publishing', 'published', 'failed', name='publicationstatus'), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_jobs_batch_id'), 'publication_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_content_id'), 'publication_jobs', ['content_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_website_key'), 'publication_jobs', ['website_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_jobs_website_key'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_content_id'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_batch_id'), table_name='publication_jobs')
    op.drop_table('publication_jobs')
    op.drop_index(op.f('ix_process_card_versions_source_checksum'), table_name='process_card_versions')
    op.drop_index(op.f('ix_process_card_versions_role'), table_name='process_card_versions')
    op.drop_index(op.f('ix_process_card_versions_process_key'), table_name='process_card_versions')
    op.drop_table('process_card_versions')
    op.drop_index(op.f('ix_operational_processes_source_checksum'), table_name='operational_processes')
    op.drop_index(op.f('ix_operational_processes_process_key'), table_name='operational_processes')
    op.drop_index(op.f('ix_operational_processes_gate_id'), table_name='operational_processes')
    op.drop_index(op.f('ix_operational_processes_family'), table_name='operational_processes')
    op.drop_index(op.f('ix_operational_processes_checklist_template_id'), table_name='operational_processes')
    op.drop_table('operational_processes')
    op.drop_index('ix_metric_snapshots_source_date', table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_entity_key'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_brand'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_listing_sync_records_own_id'), table_name='listing_sync_records')
    op.drop_table('listing_sync_records')
    op.drop_index(op.f('ix_integration_runs_source'), table_name='integration_runs')
    op.drop_index(op.f('ix_integration_runs_entity_key'), table_name='integration_runs')
    op.drop_table('integration_runs')
    op.drop_index(op.f('ix_checklist_templates_template_id'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_process_key'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_primary_role'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_gate_id'), table_name='checklist_templates')
    op.drop_index(op.f('ix_checklist_templates_checksum'), table_name='checklist_templates')
    op.drop_table('checklist_templates')
    op.drop_index(op.f('ix_checklist_instances_template_id'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_role'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_process_key'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_object_id'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_instance_id'), table_name='checklist_instances')
    op.drop_index(op.f('ix_checklist_instances_gate_id'), table_name='checklist_instances')
    op.drop_table('checklist_instances')
    op.drop_index(op.f('ix_business_profile_reviews_location_id'), table_name='business_profile_reviews')
    op.drop_index('ix_business_profile_reviews_location', table_name='business_profile_reviews')
    op.drop_index(op.f('ix_business_profile_reviews_brand'), table_name='business_profile_reviews')
    op.drop_index(op.f('ix_business_profile_reviews_account_id'), table_name='business_profile_reviews')
    op.drop_table('business_profile_reviews')
    op.drop_index(op.f('ix_business_profile_locations_location_id'), table_name='business_profile_locations')
    op.drop_index(op.f('ix_business_profile_locations_brand'), table_name='business_profile_locations')
    op.drop_index(op.f('ix_business_profile_locations_account_id'), table_name='business_profile_locations')
    op.drop_table('business_profile_locations')
    # ### end Alembic commands ###
