worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format staging '$remote_addr - $host [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent"';
  access_log /dev/stdout staging;

  server_tokens off;
  sendfile on;
  tcp_nopush on;
  keepalive_timeout 20s;
  client_max_body_size 2m;

  client_body_temp_path /tmp/client_body;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;

  map $host $site_root {
    default "";
    localhost _portal;
    127.0.0.1 _portal;
    imperial.localhost imperial;
    danish-fabrik.localhost danish-fabrik;
    bautica.localhost bautica;
    prefab.localhost prefab;
    casa-moderna.localhost casa-moderna;
    family-homes.localhost family-homes;
    everyday-homes.localhost everyday-homes;
    property-360.localhost property-360;
    budapesti-magasepito-vallalat.localhost budapesti-magasepito-vallalat;
    baufreund.localhost baufreund;
    red-property.localhost red-property;
    timberhaus.localhost timberhaus;
  }

  include /etc/nginx/conf.d/*.conf;
}
