apiVersion: v1
kind: Secret
metadata:
  name: imperial-itep-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://USER:PASSWORD@HOST:5432/itep?schema=public"
  DEFAULT_CONTACT_EMAIL: "office@example.com"
  IDENTITY_SHARED_SECRET: "replace-with-32-plus-character-secret"
